import Head from "next/head";
import styled from "styled-components";
import Cart from "../components/Cart";
import CoinSection from "../components/CoinSection";
import ProductSection from "../components/ProductSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection>
        <CoinSection />
        <Cart />
        <ProductSection />
      </MainSection>
    </>
  );
}

const MainSection = styled.main`
  display: flex;
  top: 0;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;
